### ISSUE TITLE
what do you think of the new clickgui?

### ISSUE THREAD

**Issue by MaxRockatasky** [Yaimsputnik5/HitlerHax-Leak2#1]
better? worse?

**Comment by master7720** [comment]
better then the old gui but it still pretty bad ima

**Comment by MaxRockatasky** [comment]
🤓

**Comment by Yaimsputnik5** [comment]
Reported for abusing the GitHub Issues section.

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

https://docs.github.com/en/site-policy/github-terms/github-community-guidelines
