### ISSUE TITLE
wassup gibson 

### ISSUE THREAD

**Issue by hentaienjoy3r** [Yaimsputnik5/HitlerHax-Leak2#2]

**Comment by Yaimsputnik5** [comment]
Reported for abusing the GitHub **Issues** section.

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

https://docs.github.com/en/site-policy/github-terms/github-community-guidelines

**Comment by Yaimsputnik5** [comment]
Reported for abusing the GitHub **Issues** section.

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service

https://docs.github.com/en/site-policy/github-terms/github-community-guidelines
